### ISSUE TITLE
Last feature in feature collection has extraneous comma

### ISSUE THREAD

**Issue by skorasaurus** [openaddresses/pyesridump#1]
Thank you for making this Ian. 

The last feature obtained contains an extraneous comma which breaks most parsers and validators.

See as an example. https://github.com/opencleveland/clecrime/commit/9d3550152589be253584cea95dd2654d4119df22

**Comment by iandees** [comment]
Hmm, the best thing to do is probably to install https://github.com/openaddresses/machine:

```bash
git clone https://github.com/openaddresses/machine
cd machine
python setup.py install
```

...and then run `openaddr-esri2geojson <esri_url> <output_geojson_filename>`

I've been keeping the ESRI-related stuff up to date in machine and not here. I should probably pull it out into this repo and then use this module in machine. Until then, the above will have to work.

**Comment by fgregg** [comment]
@iandees I was just going to ask if we could get this on pip. Would you like some help 

1. extracting the esri stuff from machine to this repo
2. getting this repo on pypi
3. having openaddress/machine depend on an esri-dump package?

**Comment by fgregg** [comment]
Actually, it doesn't look like the `openaddr-esri2geojson` has the same subdivision strategy. Instead it looks like it tries to [enumerate all the object ids and paginate through them](https://github.com/openaddresses/machine/blob/master/openaddr/cache.py#L568).

Unfortunately, that depends upon the server supporting the `ReturnIdsOnly` argument, which was added in [ArcGIS REST Server v.10](https://developers.arcgis.com/silverlight/api-reference/ESRI.ArcGIS.Client~ESRI.ArcGIS.Client.Tasks.Query~ReturnIdsOnly.html). 

The subdivide method used in this repo will work with older versions. Why is the subdivide method not in `openaddr-esri2geojson`?

**Comment by iandees** [comment]
@fgregg Good timing! We were actually just thinking about extracting the esri2geojson bits from machine and making a separate module.

I'm planning on starting on it tomorrow morning. If I run out of time or something I'll ping you and take you up on your offer for help!

**Comment by fgregg** [comment]
I actually had some time today. Let me push up where I got.

**Comment by iandees** [comment]
I made a repo here: https://github.com/openaddresses/py-esri-dump

**Comment by iandees** [comment]
The extraneous comma has been destroyed!
