### ISSUE TITLE
Use case: Script didn't grab all features of this map layer

### ISSUE THREAD

**Issue by stevevance** [openaddresses/pyesridump#14]
[Industrial Growth Zones](http://gis1.cookcountyil.gov/GrowthZones/), hosted on the Cook County ArcGIS server

````
http://gis1.cookcountyil.gov/arcgis/rest/services/EconDevSrvc_IndustrialGrowthZones/MapServer/1
````

The script grabs only 5 out of the 7 features. 

In the terminal the script responds:
````
 cli.esridump - INFO - Built 1 requests using OID where clause method
````

Do you know how I can get the other 2 features?

**Comment by iandees** [comment]
Can you try upgrading? It looks like 2 of the 7 features are MultiPolygons, which the older code might not have been able to handle properly.

**Comment by stevevance** [comment]
Yeah, I'll upgrade but I used the version from `pip` that I installed just last night.

**Comment by iandees** [comment]
Hmm, that should be the most recent version unless I fixed something without deploying.

I did just try it locally and it seems to have worked without a problem.
