### ISSUE TITLE
Dates are converted to timestamps far in the future

### ISSUE THREAD

**Issue by stevevance** [openaddresses/pyesridump#2]
In the Chicago zoning boundaries endpoint [on this ArcGIS server](http://gisapps.cityofchicago.org/arcgis/rest/services/ExternalApps/Zoning/MapServer/1), there are at least two `esriFieldTypeDate` fields that are converted to timestamps. 

````
EDIT_DATE ( type: esriFieldTypeDate , alias: EDIT_DATE , length: 36 )
CREATE_DATE ( type: esriFieldTypeDate , alias: CREATE_DATE , length: 36 )
````

A sample value is `1033603200000`, which is equivalent to `08/02/34723 @ 12:00am (UTC)`. 

Is your script or ESRI mis-converting the date values?

**Comment by fgregg** [comment]
These are milliseconds. Just slice off 1000

**Comment by stevevance** [comment]
@fgregg I did that, making `103360320`, and I get the date `04/11/1973 @ 7:12am (UTC)`

**Comment by stevevance** [comment]
@fgregg That's what I thought, and I was dumbly truncating it by 4 digits, instead of dividing. My bad ;)

**Comment by iandees** [comment]
I'm probably not going to do any date conversion in this code. If you want to apply some knowledge for what the date formatting should be, you can parse the output from this script further.
