### ISSUE TITLE
Handle proxy URLs

### ISSUE THREAD

**Issue by iandees** [openaddresses/pyesridump#23]
Some OpenAddresses sources are Esri layers behind an HTTP proxy. The URL ends up looking like this:

```
http://map.sccmo.org/proxy/proxy.ashx?http://10.10.143.115/scc_gis/rest/services/appservices/taxinformation/MapServer/0
```

[from this build run](http://s3.amazonaws.com/data.openaddresses.io/runs/113997/output.txt)

This URL currently gets parsed by the `requests` library and turns into a request like this:

```
http://map.sccmo.org/proxy/proxy.ashx?http://10.10.143.115/scc_gis/rest/services/appservices/taxinformation/MapServer/0&f=json
```

...which doesn't work, because the `f=json` gets passed as a query arg to the proxy.ashx script instead of getting sent to the Esri endpoint.

**Comment by marhensa** [comment]
same problem here

**Comment by ingalls** [comment]
I think this should be fixed by: https://github.com/openaddresses/pyesridump/pull/38

@iandees are we ok to close?

**Comment by iandees** [comment]
Yea, I think so.
