### ISSUE TITLE
This query returns 26 duplicates for every feature

### ISSUE THREAD

**Issue by stevevance** [openaddresses/pyesridump#39]
````
esri2geojson -f ICN,TotalInjured,OInjuries,AInjuries,BInjuries,CInjuries,CrashInjurySeverity,IsHitAndRun,ContribCausePrim,ContribCauseSec,CrashReportCity,CrashDateTimeText,TotalFatals,FunctionalClassCIS,TypeOfFirstCrash,IsAnyCitation,CrashVehicleCount,AgencyCrashReportNo,IsAlcoholRelated,CISCrashID -p "where=CrashReportCity%3D%27Chicago%27" http://ags10s1.dot.illinois.gov/ArcGIS/rest/services/SafetyPortal/SafetyPortal/MapServer/12 idotcrashes5.geojson
````
````
cli.esridump - INFO - Built 26 requests using OID enumeration method
````

This will return 26 records for each of 1,000 features. This should only return 12,552 unique records, according to a simple count using [this ArcGIS server's web interface](http://ags10s1.dot.illinois.gov/ArcGIS/rest/services/SafetyPortal/SafetyPortal/MapServer/12/query?text=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&objectIds=&where=CrashReportCity%3D%27Chicago%27&time=&returnCountOnly=true&returnIdsOnly=false&returnGeometry=true&maxAllowableOffset=&outSR=&outFields=&f=html). 

`CISCrashID` is the ObjectID for this table and this screenshot shows how this one crash ID appears 26 times in the completed GeoJSON file.

<img width="655" alt="screenshot 2017-05-20 14 28 35" src="https://cloud.githubusercontent.com/assets/1330459/26278789/9e9941fc-3d68-11e7-9662-c092a045338d.png">

**Comment by iandees** [comment]
Overriding the "where" parameter means that esri2geojson can't do its job. I suppose we could add support for appending to the `where` clause, but for now you'll need to remove the `-f "where...` and do filtering later.

**Comment by stevevance** [comment]
@iandees okay, but in this case I added the WHERE because the request timed out before it could grab everything. I was doing this, and setting the fields to grab, to reduce how much data the ArcGIS server needed to transfer.

**Comment by iandees** [comment]
@stevevance if you `pip install -U esridump` in the virtualenv you created it should work.
