### ISSUE TITLE
option to force windowed id method instead of pagination

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/pyesridump#62]
There are a bunch of issues here relating to server timeout etc. From testing, I've found it's faster and likely less intensive on the server, leading to less chance of a timeout by using a windowed WHERE clause on an ID instead of paginating WHERE 1=1.

I noticed the code at 

https://github.com/openaddresses/pyesridump/blob/378155816559134b8d2b3de0d0f2fddc74f23fcd/esridump/dumper.py#L306-L331

If the server supports pagination, it will use that instead of windowed ID. We should expose an option to allow the user to force windowed ID even if pagination is supported.

**Comment by iandees** [comment]
I'm ok with adding this as an option. I think the performance of each kind of pagination depends on the backend database that Esri connects to.
