### ISSUE TITLE
Keep SR from the server

### ISSUE THREAD

**Issue by latot** [openaddresses/pyesridump#77]
Hi hi, checking:

https://github.com/openaddresses/pyesridump/blob/master/esridump/dumper.py

Is great can change the SR, but, I think the default value, or at least as an option, is to keep the SR from the server.

Why? Any transformation, even from the server have "price", so, can keep the original data is great and transform when we want or need. There is cases like WKT2, where a new way to set CRS is out, there can be a better way to transform, here the original data is even more precious.

Thx.

**Comment by iandees** [comment]
This code is designed to output GeoJSON, which [is defined](https://datatracker.ietf.org/doc/html/rfc7946#section-4) to use a geographic projection, so we ask the server to transform everything to that.
