### ISSUE TITLE
[BUG] Timeout default value

### ISSUE THREAD

**Issue by latot** [openaddresses/pyesridump#78]
Hi hi, actually the project do this:

dumper.py
```
timeout=None
...
self._http_timeout = timeout or 30
```

The ```None``` value, is a valid value for ```request```, means, without a limit timeout, so, set the initial timeout value to ```None``` cause we can't disable it.

Thx.

**Comment by iandees** [comment]
All network requests should have a timeout, so I don't consider this a bug. If you'd like, you could set to a large number. In practice, though, some part of the request chain will probably have a timeout around 30 seconds.
