### ISSUE TITLE
page_size is being limited to 1000 for servers which support maxRecordCount >1000

### ISSUE THREAD

**Issue by gangerang** [openaddresses/pyesridump#84]
The default maxRecordCount value can be values larger than 1000, with 2000 being another default value.
The current implemetation of dumper.py appears to use a page_size value which is the minimum of 1000 and the layers maxRecordCount. This means when for layers with a maxRecordCount of 2000, requests are still only made in groups of 1000 records.

Is there a reason for this limiting, or could it be changed to the maximum of 1000 and the layer maxRecordCount?

Relevant line being:
`page_size = min(1000, metadata.get('maxRecordCount', 500))`

**Comment by iandees** [comment]
I imagine this was me trying to cap the amount of work per request. If you want to submit a PR to make it 2500 or something instead, I'd appreciate it.

**Comment by gangerang** [comment]
Cheers @ramSeraph !
