### ISSUE TITLE
Unable to get untransformed ESRI JSON data

### ISSUE THREAD

**Issue by taxProper-bryan** [openaddresses/pyesridump#98]
Hi there, it seems that the dumper automatically converts the ESRI JSON to GeoJSON when iterating through the features (https://github.com/openaddresses/pyesridump/blob/master/esridump/dumper.py#L505). It would be great if the iterator could could be configured to return ESRI JSON in place of GeoJSON. Basically, this could be a configuration parameter that yields the JSON as is, if enabled, and defaults to calling `esri2geojson` if not. Could put together a PR for this if if this is something that sounds useful.

**Comment by iandees** [comment]
Sure, I'd take a look at a PR that did this.

**Comment by taxProper-bryan** [comment]
Great. Added #99 to add an `output_format` option.

**Comment by taxProper-bryan** [comment]
#99 has been merged.
